### ISSUE TITLE
Incompatible with latest beta

### ISSUE THREAD

**Issue by Cupbox** [matthayes/anki_progress_stats#25]
Throws following upon trying to open the statistics page. [Changes](https://betas.ankiweb.net/#/)
Debug info:
Anki 2.1.24 (9dda5cf6) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-03-23 20:47:52

Caught exception:
Traceback (most recent call last):
  File "aqt\main.py", line 1017, in onStats
  File "aqt\__init__.py", line 94, in open
  File "aqt\stats.py", line 52, in __init__
  File "aqt\stats.py", line 97, in refresh
  File "lib\site-packages\anki\stats.py", line 131, in report
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-76>", line 2, in easeGraph
  File "lib\site-packages\anki\hooks.py", line 640, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 637, in repl
  File "C:\Users\Johns\AppData\Roaming\Anki2\addons21\266436365\progress_stats\graphs.py", line 57, in progressGraphs
    stats = get_stats(
  File "C:\Users\Johns\AppData\Roaming\Anki2\addons21\266436365\progress_stats\compute.py", line 251, in get_stats
    all_reviews_for_bucket = _get_reviews(
  File "C:\Users\Johns\AppData\Roaming\Anki2\addons21\266436365\progress_stats\compute.py", line 126, in _get_reviews
    result = func(query, bucket_size_days=bucket_size_days, day_cutoff_seconds=day_cutoff_seconds)
TypeError: all() got an unexpected keyword argument 'bucket_size_days'

**Comment by matthayes** [comment]
Thanks for the report.  I'll look into it.

**Comment by matthayes** [comment]
I figured out the issue and uploaded a new version (0.15) that works with the latest beta.

**Comment by Cupbox** [comment]
Thank you!
